name: Build and Verify for ino_dev

on:
  push:
    branches:
      - ino_dev
  pull_request:
    branches:
      - ino_dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build project
        run: |
          make

      - name: Test Build
        run: |
          make test

      - name: Archive built artifact
        if: success() 
        uses: actions/upload-artifact@v4
        with:
          name: cjson-build
          path: ./cJSON  
